# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d91d9a244eb27c691785c26b5567e6be32cfd5564b65430a8be9544a66042969f3b27aab39a264afdcf9d64a0764e393dc07fb134e1c06012b2a4eaeba1a8d3a

test:
  secret_key_base: c6391fb1e9a596147c44d0b56f76902d96a845cf783a04b406221ae2448d39d0e3024690e87b4330d6814d51fdcaf9620493c25d5d79996a575001e1c58165c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
